// GENERAT - nu edita manual.
//
// Toate cele 316 orașe și municipii din România (Wikipedia, lista
// orașelor din România, recensământ 2021). Înainte exista doar lista celor 41
// de reședințe de județ, deci cineva din Aiud sau Mediaș nu-și putea lista
// cartea: dropdown-ul nu accepta orașul lui.
//
// Lista trebuie să fie identică în frontend (core/constants/romanian_cities.dart)
// și backend (common/constants/romanian-cities.ts) - backend-ul validează cu
// @IsIn, deci orice divergență se traduce în listări respinse.
const List<String> kRomanianCities = [
  'Abrud',
  'Adjud',
  'Agnita',
  'Aiud',
  'Alba Iulia',
  'Aleșd',
  'Alexandria',
  'Amara',
  'Anina',
  'Aninoasa',
  'Arad',
  'Ardud',
  'Avrig',
  'Azuga',
  'Babadag',
  'Bacău',
  'Baia de Aramă',
  'Baia de Arieș',
  'Baia Mare',
  'Baia Sprie',
  'Balș',
  'Baraolt',
  'Băbeni',
  'Băicoi',
  'Băile Govora',
  'Băile Herculane',
  'Băile Olănești',
  'Băile Tușnad',
  'Băilești',
  'Bălan',
  'Bălcești',
  'Bârlad',
  'Bechet',
  'Beclean',
  'Beiuș',
  'Berbești',
  'Berești',
  'Bicaz',
  'Bistrița',
  'Blaj',
  'Bocșa',
  'Boldești-Scăeni',
  'Bolintin-Vale',
  'Borsec',
  'Borșa',
  'Botoșani',
  'Brad',
  'Bragadiru',
  'Brașov',
  'Brăila',
  'Breaza',
  'Brezoi',
  'Broșteni',
  'Bucecea',
  'București',
  'Budești',
  'Buftea',
  'Buhuși',
  'Bumbești-Jiu',
  'Bușteni',
  'Buzău',
  'Buziaș',
  'Cajvana',
  'Calafat',
  'Caracal',
  'Caransebeș',
  'Carei',
  'Cavnic',
  'Călan',
  'Călărași',
  'Călimănești',
  'Căzănești',
  'Câmpeni',
  'Câmpia Turzii',
  'Câmpina',
  'Câmpulung',
  'Câmpulung Moldovenesc',
  'Cehu Silvaniei',
  'Cernavodă',
  'Chișineu-Criș',
  'Chitila',
  'Ciacova',
  'Cisnădie',
  'Cluj-Napoca',
  'Codlea',
  'Comarnic',
  'Comănești',
  'Constanța',
  'Copșa Mică',
  'Corabia',
  'Costești',
  'Covasna',
  'Craiova',
  'Cristuru Secuiesc',
  'Cugir',
  'Curtea de Argeș',
  'Curtici',
  'Darabani',
  'Dăbuleni',
  'Dărmănești',
  'Dej',
  'Deta',
  'Deva',
  'Dolhasca',
  'Dorohoi',
  'Dragomirești',
  'Drăgănești-Olt',
  'Drăgășani',
  'Drobeta-Turnu Severin',
  'Dumbrăveni',
  'Eforie',
  'Făgăraș',
  'Făget',
  'Fălticeni',
  'Făurei',
  'Fetești',
  'Fieni',
  'Fierbinți-Târg',
  'Filiași',
  'Flămânzi',
  'Focșani',
  'Frasin',
  'Fundulea',
  'Galați',
  'Găești',
  'Gătaia',
  'Geoagiu',
  'Gheorgheni',
  'Gherla',
  'Ghimbav',
  'Giurgiu',
  'Gura Humorului',
  'Hațeg',
  'Hârlău',
  'Hârșova',
  'Horezu',
  'Huedin',
  'Hunedoara',
  'Huși',
  'Ianca',
  'Iași',
  'Iernut',
  'Ineu',
  'Isaccea',
  'Însurăței',
  'Întorsura Buzăului',
  'Jibou',
  'Jimbolia',
  'Lehliu Gară',
  'Lipova',
  'Liteni',
  'Livada',
  'Luduș',
  'Lugoj',
  'Lupeni',
  'Mangalia',
  'Marghita',
  'Măcin',
  'Măgurele',
  'Mărășești',
  'Medgidia',
  'Mediaș',
  'Miercurea Ciuc',
  'Miercurea Nirajului',
  'Miercurea Sibiului',
  'Mihăilești',
  'Milișăuți',
  'Mioveni',
  'Mizil',
  'Moinești',
  'Moldova Nouă',
  'Moreni',
  'Motru',
  'Murfatlar',
  'Murgeni',
  'Nădlac',
  'Năsăud',
  'Năvodari',
  'Negrești',
  'Negrești-Oaș',
  'Negru Vodă',
  'Nehoiu',
  'Novaci',
  'Nucet',
  'Ocna Mureș',
  'Ocna Sibiului',
  'Ocnele Mari',
  'Odobești',
  'Odorheiu Secuiesc',
  'Oltenița',
  'Onești',
  'Oradea',
  'Oravița',
  'Orăștie',
  'Orșova',
  'Otopeni',
  'Oțelu Roșu',
  'Ovidiu',
  'Panciu',
  'Pantelimon',
  'Pașcani',
  'Pătârlagele',
  'Pâncota',
  'Pecica',
  'Petrila',
  'Petroșani',
  'Piatra Neamț',
  'Piatra-Olt',
  'Pitești',
  'Ploiești',
  'Plopeni',
  'Podu Iloaiei',
  'Pogoanele',
  'Popești-Leordeni',
  'Potcoava',
  'Predeal',
  'Pucioasa',
  'Răcari',
  'Rădăuți',
  'Râmnicu Sărat',
  'Râmnicu Vâlcea',
  'Râșnov',
  'Recaș',
  'Reghin',
  'Reșița',
  'Roman',
  'Roșiorii de Vede',
  'Rovinari',
  'Roznov',
  'Rupea',
  'Salcea',
  'Salonta',
  'Satu Mare',
  'Săcele',
  'Săcueni',
  'Săliște',
  'Săliștea de Sus',
  'Sărmașu',
  'Săveni',
  'Sângeorgiu de Pădure',
  'Sângeorz-Băi',
  'Sânnicolau Mare',
  'Sântana',
  'Scornicești',
  'Sebeș',
  'Segarcea',
  'Seini',
  'Sfântu Gheorghe',
  'Sibiu',
  'Sighetu Marmației',
  'Sighișoara',
  'Simeria',
  'Sinaia',
  'Siret',
  'Slatina',
  'Slănic',
  'Slănic Moldova',
  'Slobozia',
  'Solca',
  'Sovata',
  'Strehaia',
  'Suceava',
  'Sulina',
  'Șimleu Silvaniei',
  'Șomcuta Mare',
  'Ștefănești',
  'Ștei',
  'Tălmaciu',
  'Tășnad',
  'Tăuții-Măgherăuș',
  'Târgoviște',
  'Târgu Bujor',
  'Târgu Cărbunești',
  'Târgu Frumos',
  'Târgu Jiu',
  'Târgu Lăpuș',
  'Târgu Mureș',
  'Târgu Neamț',
  'Târgu Ocna',
  'Târgu Secuiesc',
  'Târnăveni',
  'Techirghiol',
  'Tecuci',
  'Teiuș',
  'Timișoara',
  'Tismana',
  'Titu',
  'Toplița',
  'Topoloveni',
  'Tulcea',
  'Turda',
  'Turnu Măgurele',
  'Țăndărei',
  'Țicleni',
  'Ulmeni',
  'Ungheni',
  'Uricani',
  'Urlați',
  'Urziceni',
  'Valea lui Mihai',
  'Vaslui',
  'Vașcău',
  'Vatra Dornei',
  'Vălenii de Munte',
  'Vânju Mare',
  'Vicovu de Sus',
  'Victoria',
  'Videle',
  'Vișeu de Sus',
  'Vlăhița',
  'Voluntari',
  'Vulcan',
  'Zalău',
  'Zărnești',
  'Zimnicea',
  'Zlatna',
];
