// Reședințe de județ + București. Extindem lista mai târziu dacă e nevoie
// de orașe mai mici - momentan suficient pentru un MVP unde distanța
// dintre utilizatori contează la nivel de oraș mare.

export const ROMANIAN_CITIES = [
  'Alba Iulia',
  'Arad',
  'Pitești',
  'Bacău',
  'Oradea',
  'Bistrița',
  'Botoșani',
  'Brașov',
  'Brăila',
  'București',
  'Buzău',
  'Reșița',
  'Călărași',
  'Cluj-Napoca',
  'Constanța',
  'Sfântu Gheorghe',
  'Târgoviște',
  'Craiova',
  'Galați',
  'Giurgiu',
  'Târgu Jiu',
  'Miercurea Ciuc',
  'Deva',
  'Slobozia',
  'Iași',
  'Baia Mare',
  'Drobeta-Turnu Severin',
  'Târgu Mureș',
  'Piatra Neamț',
  'Slatina',
  'Ploiești',
  'Satu Mare',
  'Zalău',
  'Sibiu',
  'Suceava',
  'Alexandria',
  'Timișoara',
  'Tulcea',
  'Vaslui',
  'Râmnicu Vâlcea',
  'Focșani',
] as const;

export type RomanianCity = (typeof ROMANIAN_CITIES)[number];
